(function(root){
  const text=(key,label,help='',options={})=>({key,label,help,type:'text',...options});
  const number=(key,label,min,max,step=1,help='')=>({key,label,type:'number',min,max,step,help});
  const select=(key,label,options,help='')=>({key,label,type:'select',options,help});
  const secret=(key,label)=>text(key,label,'کلید در همین مرورگر ذخیره می‌شود.',{type:'password'});
  const lines=(key,label,help)=>text(key,label,help,{type:'lines',wide:true});
  const area=(key,label,help='',maxLength=6000)=>text(key,label,help,{type:'textarea',wide:true,maxLength});
  const check=(key,label,help='')=>({key,label,type:'checkbox',help});
  const groups=[
    {id:'routing',title:'مسیر پردازش',description:'هر مرحله مستقل است. انتخاب مدل جدید روی پروژه‌های جدید اعمال می‌شود؛ برای عوض‌کردن سرویس صدای پروژهٔ قبلی، فایل را با تنظیمات جدید پردازش کنید.',fields:[
      select('sttProvider','گفتار به متن',[['auto','خودکار · Deepgram برای فایل / Groq برای ضبط'],['deepgram','Deepgram'],['groq','Groq Whisper'],['elevenlabs','ElevenLabs Scribe'],['gemini','Gemini · تحلیل صوت با زمان تخمینی'],['openai','OpenAI']]),
      select('translationProvider','ترجمهٔ متن',[['groq','Groq'],['gemini','Gemini'],['openai','OpenAI']]),select('ttsProvider','متن به صدا',[['fish','Fish Audio'],['elevenlabs','ElevenLabs'],['gemini','Gemini'],['openai','OpenAI']]),text('sourceLanguage','زبان گفتار','کد زبان مثل en یا fa؛ خالی برای تشخیص خودکار در سرویس‌های پشتیبان.',{maxLength:12}),check('autoSpeakerVoices','انتخاب خودکار صدا برای هر گوینده','اختیاری: هر خط فهرست صداها برای یک گوینده است. گویندهٔ بدون Voice ID از صدای پیش‌فرض استفاده می‌کند. برای YouTube، تشخیص گوینده هنگام ضبط را هم فعال کنید.'),check('speakerMode','تشخیص گوینده هنگام ضبط YouTube','دریافت زیرنویس کنار گذاشته می‌شود و صدا به STT انتخاب‌شده ارسال می‌شود. هویت گوینده بین پنجره‌های ضبط تضمین نمی‌شود.')
    ]},
    {id:'eleven',title:'ElevenLabs',description:'Scribe برای تشخیص و زمان‌بندی گفتار؛ مدل TTS و صدا مستقل انتخاب می‌شوند. دسترسی مدل و Voice ID به حساب وابسته است.',fields:[secret('elevenApiKey','API Key'),text('elevenVoiceId','Voice ID'),text('elevenTtsModel','مدل TTS','مدل باید از زبان فارسی پشتیبانی کند.',{suggestions:['eleven_v3','eleven_multilingual_v2','eleven_flash_v2_5','eleven_turbo_v2_5']}),text('elevenSttModel','مدل STT','Scribe با برچسب گوینده و زمان کلمات.',{suggestions:['scribe_v2','scribe_v1']}),number('elevenStability','ثبات صدا',0,1,.01,'برای eleven_v3 معمولاً ۰، ۰٫۵ یا ۱ انتخاب می‌شود.'),number('elevenSimilarity','شباهت صدا',0,1,.01),number('elevenStyle','شدت سبک',0,1,.01),number('elevenSpeed','سرعت گفتار',.7,1.2,.01),number('elevenNumSpeakers','حداکثر گوینده‌ها',0,32,1,'۰ = تشخیص خودکار'),check('elevenSpeakerBoost','تقویت شباهت گوینده','اثر پارامترهای صدا به مدل وابسته است.'),lines('elevenSpeakerVoices','صدای هر گوینده','هر خط یک Voice ID؛ خط اول گوینده ۱. این نگاشت فقط برای ElevenLabs است.') ]},
    {id:'gemini',title:'Gemini',description:'ترجمه با مدل متنی؛ STT از تحلیل صوت تولید می‌شود و زمان‌بندی/هویت آن باید بازبینی شود. مسیر inline صوت تا ۱۴ مگابایت است. TTS 3.8 از Interactions و TTS 2.5 از generateContent استفاده می‌کند.',fields:[secret('geminiApiKey','API Key'),text('geminiTranslationModel','مدل ترجمه','شناسهٔ مدل دارای خروجی JSON.',{suggestions:['gemini-3.8-flash','gemini-3.8-pro','gemini-2.5-flash']}),text('geminiSttModel','مدل تحلیل صوت','زمان‌بندی تخمینی؛ برای فایل کوچک‌تر از ۱۴ مگابایت.',{suggestions:['gemini-3.8-flash','gemini-2.5-flash']}),text('geminiTtsModel','مدل TTS','شناسهٔ یک مدل تولید گفتار.',{suggestions:['gemini-3.8-flash-tts','gemini-3.8-flash-lite-tts','gemini-2.5-flash-preview-tts','gemini-2.5-pro-preview-tts']}),text('geminiVoice','صدای پیش‌فرض','نام صدای آمادهٔ Gemini.',{suggestions:['Kore','Puck','Charon','Fenrir','Aoede','Leda','Orus','Zephyr']}),lines('geminiSpeakerVoices','صدای هر گوینده','هر خط یک نام صدا، مثل Kore یا Puck. خط اول گوینده ۱.') ]},
    {id:'openai',title:'OpenAI · فایل و متن',description:'مدل diarize برچسب گوینده دارد؛ whisper-1 زمان‌بندی دارد ولی گوینده‌ها را جدا نمی‌کند. سقف فایل STT در این مسیر ۲۵ مگابایت است. صداهای تولیدشده مصنوعی‌اند.',fields:[secret('openaiApiKey','API Key'),text('openaiTranslationModel','مدل ترجمه','مدل پشتیبان Chat Completions و JSON Schema.',{suggestions:['gpt-4.1-mini','gpt-4.1','gpt-4o-mini']}),select('openaiSttModel','مدل STT زمان‌بندی‌شده',[['gpt-4o-transcribe-diarize','GPT-4o Transcribe Diarize'],['whisper-1','Whisper · بدون تفکیک گوینده']]),text('openaiTtsModel','مدل TTS','مدل‌های بدون instructions آن را دریافت نمی‌کنند.',{suggestions:['gpt-4o-mini-tts','tts-1','tts-1-hd']}),text('openaiVoice','صدای پیش‌فرض','نام صدا باید با مدل سازگار باشد.',{suggestions:['coral','marin','cedar','alloy','ash','ballad','echo','fable','nova','onyx','sage','shimmer','verse']}),lines('openaiSpeakerVoices','صدای هر گوینده','هر خط یک نام صدا؛ نگاشت مستقل از سرویس‌های دیگر.') ]},
    {id:'live',title:'ارتباط زنده · تنظیمات پیشرفته',description:'از صفحهٔ ترجمهٔ زنده، میکروفون یا صدای تب اشتراک‌گذاشته‌شده را وصل کنید. GPT-Live، OpenAI Realtime و Gemini Live مسیرهای جدا هستند. این جلسات خروجی WAV/SRT پروژه تولید نمی‌کنند و کیفیت ترجمه و تأخیر وابسته به مدل است.',fields:[select('liveProvider','سرویس زنده',[['gemini','Gemini Live'],['openai-realtime','OpenAI Realtime'],['openai-live','GPT-Live']]),select('liveInput','ورودی صدا',[['microphone','میکروفون'],['tab','تب اشتراک‌گذاشته‌شده']]),text('geminiLiveModel','مدل Gemini Live','مدل دارای native audio.',{suggestions:['gemini-3.8-live','gemini-2.5-flash-native-audio-preview-12-2025']}),text('geminiLiveVoice','صدای Gemini Live','نام صدا، مثل Kore.'),text('openaiRealtimeModel','مدل OpenAI Realtime','مدل دارای صوت Realtime.',{suggestions:['gpt-realtime-2.1','gpt-realtime-2.1-mini','gpt-realtime']}),text('openaiRealtimeVoice','صدای OpenAI Realtime','پس از شروع جلسه تغییر صدا نیازمند جلسهٔ جدید است.',{suggestions:['marin','cedar','alloy','ash','ballad','coral','echo','sage','shimmer','verse']}),text('openaiLiveModel','مدل GPT-Live','پشتیبانی از /v1/live/sessions؛ دسترسی حساب لازم است.',{suggestions:['gpt-live-1']}),text('openaiLiveBackendModel','مدل پشتیبان GPT-Live','Responses delegation؛ مصرف آن جدا محاسبه می‌شود.',{suggestions:['gpt-5.6-terra','gpt-4.1-mini']}),number('liveVadThreshold','آستانهٔ تشخیص گفتار Realtime',0,1,.01),number('liveSilenceMs','سکوت تا پایان گفتار · میلی‌ثانیه',100,2000,50,'در Gemini و Realtime اعمال می‌شود؛ GPT-Live پایان گفتار را مدیریت می‌کند.'),number('livePrefixMs','صدای قبل از شروع گفتار · میلی‌ثانیه',0,1000,50,'برای Gemini و Realtime'),number('liveMaxMinutes','قطع خودکار جلسه · دقیقه',1,60),check('liveTranscripts','نمایش متن ورودی و خروجی زنده','متن در صفحه نمایش داده می‌شود و در فایل ذخیره نمی‌شود.'),area('liveInstructions','دستور جلسهٔ زنده','پیش‌فرض فقط ترجمه می‌کند. تغییر این دستور می‌تواند رفتار جلسه را به گفت‌وگو تبدیل کند.',4000) ]},
    {id:'fish',title:'Fish Audio',description:'تنظیمات قبلی حفظ شده‌اند. این گزینه‌ها فقط وقتی Fish برای تولید صدا انتخاب شده اثر دارند.',fields:[lines('fishApiKeys','API Keys','هر خط یک کلید؛ هنگام خطای اعتبار، کلید بعدی بررسی می‌شود.'),text('fishVoiceId','Voice ID یا لینک صدا'),text('fishModel','مدل TTS','شناسهٔ مدل Fish.',{suggestions:['s2.1-pro-free']}),select('fishLatency','تأخیر',[['low','کم'],['balanced','متعادل'],['normal','معمولی']]),select('ttsBitrate','کیفیت MP3 · kbps',[['64','64'],['128','128'],['192','192']]),lines('speakerVoices','صدای هر گویندهٔ Fish','هر خط یک Voice ID؛ خط اول گوینده ۱.') ]},
    {id:'existing',title:'Deepgram و Groq',description:'تشخیص گفتار و ترجمهٔ فعلی همچنان قابل انتخاب‌اند.',fields:[secret('deepgramApiKey','Deepgram API Key'),secret('groqApiKey','Groq API Key'),text('whisperModel','مدل Groq STT','مدل دارای زمان‌بندی segment.',{suggestions:['whisper-large-v3-turbo','whisper-large-v3']}),text('groqTranslationModel','مدل Groq ترجمه','مدل باید از JSON Schema پشتیبانی کند.',{suggestions:['openai/gpt-oss-120b','openai/gpt-oss-20b']}) ]},
    {id:'language',title:'لحن، زمینه و تلفظ',description:'زمینه و واژه‌نامه به سرویس ترجمهٔ انتخاب‌شده می‌روند. قواعد تلفظ فقط متن ارسالی به TTS را تغییر می‌دهند.',fields:[select('translationStyle','لحن ترجمه',[['natural','طبیعی و محاوره‌ای'],['formal','رسمی'],['cinematic','سینمایی']]),number('translationTemperature','تنوع ترجمه',0,1,.05,'برای Gemini و OpenAI؛ Groq از مقدار ثابت ۰٫۱۵ استفاده می‌کند.'),area('translationGlossary','واژه‌نامه','هر خط source = معادل فارسی'),area('projectNotes','زمینهٔ پروژه','موضوع، مخاطب و توضیح نام‌ها.',4000),area('pronunciationRules','اصلاح تلفظ','هر خط عبارت = تلفظ نوشتاری'),area('ttsInstructions','دستور لحن صدا','برای Gemini و OpenAI؛ روی متن زیرنویس اثر ندارد.',2000),number('ttsSpeed','سرعت TTS OpenAI',.25,4,.05) ]},
    {id:'engine',title:'پردازش و پخش',description:'تعداد درخواست هم‌زمان و تکه‌بندی را متناسب با محدودیت حساب تنظیم کنید. تغییر این تنظیمات دقت سرویس را تضمین نمی‌کند.',fields:[number('fishConcurrency','درخواست‌های هم‌زمان TTS · همهٔ سرویس‌ها',1,10),number('fishRetries','تلاش مجدد Fish',0,8),number('chunkTargetSec','مدت هدف جمله · ثانیه',3,20),number('chunkMaxSec','حداکثر مدت جمله · ثانیه',3,30),number('chunkMaxChars','حداکثر نویسهٔ جمله',60,900),number('maxTimeStretch','حداکثر سرعت پخش دوبلهٔ YouTube',1,3,.05),number('fallbackCaptureSec','پنجرهٔ ضبط YouTube · ثانیه',5,30),check('showPersianSubtitles','نمایش زیرنویس فارسی'),check('autoApplyWhenReady','پخش خودکار پس از آماده‌شدن') ]}
  ];
  groups.find(g=>g.id==='live').fields.splice(8,0,text('openaiLiveVoice','صدای GPT-Live','صدای پشتیبان یا صدای سفارشی مجاز؛ تغییر آن به جلسهٔ جدید نیاز دارد.',{suggestions:['marin','cedar']}));
  const routing=groups.find(g=>g.id==='routing')||groups[0];
  routing.fields.find(f=>f.key==='ttsProvider').options.push(['local','مدل محلی · OpenAI-compatible']);
  routing.fields.find(f=>f.key==='sttProvider').options.push(['local','مدل محلی · OpenAI-compatible']);
  routing.fields.push(check('ttsAutoSelect','استفاده خودکار از تنها کلید TTS موجود','اگر سرویس انتخاب‌شده کلید ندارد و فقط یک سرویس TTS کلید دارد، همان استفاده می‌شود. با چند کلید انتخاب صریح حفظ می‌شود. Voice ID سرویس مربوط هم لازم است. مدل محلی فقط با انتخاب مستقیم فعال می‌شود.'));
  groups.find(g=>g.id==='gemini').description='ترجمهٔ ساختاریافته، تحلیل صوت با زمان‌بندی تخمینی و TTS با مسیر مستقل مدل‌های ۳.۸ و ۲.۵. فایل‌های بزرگ صوتی خودکار با Files API آپلود و پس از پردازش حذف می‌شوند.';
  groups.find(g=>g.id==='gemini').fields.find(f=>f.key==='geminiSttModel').help='مدل تحلیل صوت با خروجی JSON؛ زمان‌بندی و تفکیک گوینده را بازبینی کنید.';
  groups.splice(4,0,{id:'local',title:'مدل محلی · STT و TTS',description:'سرور مدل باید از API سازگار با OpenAI پشتیبانی کند. آدرس پایه شامل /v1 است؛ STT و TTS می‌توانند روی پورت‌های متفاوت باشند. Ollama به‌تنهایی این مسیرهای صوتی را ارائه نمی‌کند.',fields:[text('localSttUrl','آدرس پایهٔ سرور STT','مثل http://127.0.0.1:8000/v1؛ فقط localhost یا 127.0.0.1.'),text('localSttModel','نام مدل STT','شناسهٔ مدل در سرور خودتان.'),select('localSttFormat','خروجی STT',[['verbose_json','verbose_json · زمان‌بندی جمله‌ها'],['diarized_json','diarized_json · زمان‌بندی و گوینده']]),text('localTtsUrl','آدرس پایهٔ سرور TTS','مثل http://localhost:8880/v1'),text('localTtsModel','نام مدل TTS'),text('localVoice','صدای پیش‌فرض مدل محلی'),secret('localApiKey','کلید سرور محلی · اختیاری'),lines('localSpeakerVoices','صدای محلی هر گوینده','هر خط یک شناسهٔ صدا در سرور محلی.')]});
  function validate(values){
    const out={};
    for(const field of groups.flatMap(g=>g.fields)){
      if(!Object.hasOwn(values,field.key))continue;let v=values[field.key];
      if(field.type==='number'||field.key==='ttsBitrate'){v=Number(v);if(!Number.isFinite(v)||field.type==='number'&&(v<field.min||v>field.max||field.step===1&&!Number.isInteger(v)))throw new Error(`مقدار «${field.label}» معتبر نیست.`);}
      if(field.type==='select'&&!field.options.some(x=>String(x[0])===String(v)))throw new Error(`گزینهٔ «${field.label}» معتبر نیست.`);
      if(field.type==='checkbox'&&typeof v!=='boolean')throw new Error(`مقدار «${field.label}» باید روشن یا خاموش باشد.`);
      if(field.type==='lines'){if(!Array.isArray(v)||v.length>100||v.some(x=>typeof x!=='string'||x.length>500))throw new Error(`فهرست «${field.label}» معتبر نیست.`);v=v.map(x=>x.trim());}
      else if(['text','textarea','password'].includes(field.type)){if(typeof v!=='string'||v.length>(field.maxLength||10000))throw new Error(`متن «${field.label}» بیش از حد بلند یا نامعتبر است.`);if(field.type!=='textarea')v=v.trim();}
      if(['localSttUrl','localTtsUrl'].includes(field.key)){let u;try{u=new URL(v);}catch{throw new Error(`آدرس «${field.label}» معتبر نیست.`);}if(!['http:','https:'].includes(u.protocol)||!['localhost','127.0.0.1'].includes(u.hostname)||u.username||u.password||u.search||u.hash)throw new Error('سرور محلی باید روی localhost یا 127.0.0.1 با HTTP یا HTTPS باشد.');}
      out[field.key]=v;
    }
    if(out.chunkMaxSec!=null&&out.chunkTargetSec!=null&&out.chunkMaxSec<out.chunkTargetSec)throw new Error('حداکثر مدت جمله نباید از مدت هدف کمتر باشد.');
    return out;
  }
  root.EasyTsSettings={groups,validate};if(typeof module!=='undefined')module.exports=root.EasyTsSettings;
})(globalThis);
