/* Integrated project desk; the existing offscreen engine owns all edits and synthesis. */
(() => {
  const host=document.createElement('section');host.className='workbench';host.setAttribute('aria-label','میز تدوین دوبله');
  host.innerHTML=`<header class="wb-header"><div><h2>میز تدوین دوبله</h2><p id="wbTitle">یک فایل وارد کن یا پروژهٔ قبلی را ادامه بده.</p></div><select id="wbProject" class="wb-project" aria-label="انتخاب پروژه"><option value="">پروژهٔ فعال</option></select></header><div class="wb-body"><section class="wb-stage"><div class="wb-screen"><video id="wbVideo" controls preload="metadata" hidden aria-label="پیش‌نمایش فایل منبع"></video><div id="wbEmpty" class="wb-placeholder"><img class="ui-icon" src="icons/ui/headphones.svg" alt=""><h3>اول بشنو، بعد دقیق‌ترش کن.</h3><p id="wbEmptyText">فایل صوتی یا ویدئویی را وارد کن. پس از پردازش، هر جمله روی خط زمان قابل انتخاب و ویرایش است.</p><label class="wb-upload">انتخاب فایل<input id="wbFile" type="file" accept="audio/*,video/mp4,video/webm,video/quicktime"></label></div></div><div class="wb-media-bar"><label class="wb-mode">پیش‌نمایش<select id="wbMode"><option value="source">صدای منبع</option><option value="dub" disabled>دوبلهٔ خروجی WAV</option></select></label><span id="wbMediaInfo">MP3 · WAV · MP4 · WebM</span></div><audio id="wbSourceAudio" class="wb-audio" controls hidden aria-label="پیش‌نمایش صوتی پروژه"></audio></section><aside class="wb-inspector"><h3 id="wbSelection">بازبینی یک جمله</h3><label>متن اصلی<div id="wbOriginal" class="wb-source">یک جمله را از خط زمان انتخاب کن.</div></label><label>ترجمهٔ فارسی<textarea id="wbText" maxlength="3000" disabled></textarea></label><div class="wb-times"><label>شروع · ثانیه<input id="wbStart" type="number" min="0" step=".001" disabled></label><label>پایان · ثانیه<input id="wbEnd" type="number" min="0" step=".001" disabled></label></div><label>صدای این جمله<input id="wbVoice" type="text" maxlength="180" disabled></label><div class="wb-edit-actions"><button id="wbSave" type="button" disabled>ذخیرهٔ تغییرات</button><button id="wbPreview" type="button" disabled>شنیدن جمله</button><button id="wbRegen" type="button" disabled>بازسازی صدا</button></div><audio id="wbSentenceAudio" class="wb-audio" controls hidden aria-label="صدای جملهٔ انتخاب‌شده"></audio><span id="wbEditState" class="wb-caption">متن و صدای هر جمله مستقل ویرایش می‌شوند.</span></aside></div><section class="wb-timeline"><div class="wb-timeline-header"><strong>خط زمان گوینده‌ها</strong><span id="wbTimelineInfo">جمله‌ای برای نمایش نیست</span></div><div id="wbTracks" class="wb-tracks"><div class="wb-timeline-empty">بعد از پردازش فایل، دیالوگ‌ها اینجا نمایش داده می‌شوند.</div></div></section><footer class="wb-footer"><span id="wbStatus" role="status" aria-live="polite">آمادهٔ شروع پروژه</span><button id="wbStop" type="button" hidden>توقف پردازش</button><button id="wbSrt" type="button" disabled>زیرنویس SRT</button><button id="wbRender" class="primary" type="button" disabled>ساخت خروجی WAV</button><button id="wbDownload" type="button" hidden>دریافت WAV</button><a href="studio.html">میکس و خروجی ویدئو ↗</a></footer><div id="wbError" class="wb-error" role="alert" hidden></div>`;
  document.querySelector('.dashboard-stats').after(host);
  const youtube=document.createElement('details');youtube.className='youtube-section';const summary=document.createElement('summary');summary.textContent='دوبلهٔ YouTube و وضعیت پردازش';youtube.append(summary);host.after(youtube);youtube.append(document.getElementById('tab-dub'));document.querySelector('a.new-project').href='#wbFile';
  const el=id=>document.getElementById('wb'+id);
  let job=null,selected=null,dirty=false,busy=false,working=false,refreshing=false,poll,mediaKey='',mediaSerial=0,previewSerial=0,sourceUrl=null,dubUrl=null,sentenceUrl=null,output=null;
  const phases=['starting','transcribing','translating','generating','capturing','exporting'];
  const fail=text=>{el('Error').textContent=text||'';el('Error').hidden=!text;};
  document.querySelector('a.new-project').onclick=event=>{event.preventDefault();if(dirty||busy||working){fail('ابتدا ویرایش فعلی را ذخیره کن یا منتظر پایان پردازش بمان.');return;}el('File').click();};
  async function send(type,values={}){const result=await chrome.runtime.sendMessage({type,...values});if(!result?.ok)throw new Error(result?.error||'ارتباط با افزونه برقرار نشد.');return result;}
  function controls(){const locked=busy||working;for(const id of ['Text','Start','End','Voice'])el(id).disabled=locked||!selected;el('Save').disabled=locked||!selected||!dirty;el('Regen').disabled=locked||!selected||dirty;el('Preview').disabled=locked||!selected?.ready||dirty;el('Project').disabled=locked;el('File').disabled=locked;el('Render').disabled=locked||dirty||!job?.segments?.length||job.segments.some(s=>!s.ready);el('Srt').disabled=dirty||!job?.segments?.length||job.segments.some(s=>s.translated===false);el('Download').hidden=!output||dirty;el('Stop').hidden=!busy;el('EditState').classList.toggle('wb-dirty',dirty);}
  function pauseMedia(){el('Video').pause();el('SourceAudio').pause();el('SentenceAudio').pause();}
  function release(name){const url=name==='source'?sourceUrl:name==='dub'?dubUrl:sentenceUrl;if(url)URL.revokeObjectURL(url);if(name==='source')sourceUrl=null;else if(name==='dub')dubUrl=null;else sentenceUrl=null;}
  async function media(){
    const key=job?`${job.jobKey}:${job.revision||0}:${output?.createdAt||0}`:'';if(mediaKey===key)return;mediaKey=key;const serial=++mediaSerial;pauseMedia();release('source');release('dub');release('sentence');el('SentenceAudio').hidden=true;
    el('Video').removeAttribute('src');el('Video').load();el('Video').hidden=true;el('SourceAudio').removeAttribute('src');el('SourceAudio').load();el('SourceAudio').hidden=true;el('Empty').hidden=false;el('Mode').value='source';el('Mode').options[1].disabled=!output;
    const record=job?.sourceKey?await StudioDB.get('sources',job.sourceKey):null;if(serial!==mediaSerial)return;
    if(record?.blob){sourceUrl=URL.createObjectURL(record.blob);const video=/^video\//.test(record.blob.type)||/\.(mp4|webm|mov)$/i.test(record.name||'');if(video){el('Video').src=sourceUrl;el('Video').hidden=false;el('Empty').hidden=true;}else{el('SourceAudio').src=sourceUrl;el('SourceAudio').hidden=false;el('EmptyText').textContent='فایل صوتی آمادهٔ بازبینی است. یک جمله را از خط زمان انتخاب کن.';}el('MediaInfo').textContent=record.name||'فایل منبع';}
    else el('EmptyText').textContent=job?'منبع این پروژه در کش نیست. صدای هر جمله را می‌توانی جداگانه بشنوی. برای YouTube، ویدئو در تب خودش پخش می‌شود.':'فایل را انتخاب کن تا ترجمه و دوبله در همین فضای کار آماده شوند.';
    if(output?.blob)dubUrl=URL.createObjectURL(output.blob);
  }
  function timeline(){
    el('Tracks').replaceChildren();const segments=job?.segments||[];
    if(!segments.length){const empty=document.createElement('div');empty.className='wb-timeline-empty';empty.textContent='بعد از پردازش فایل، دیالوگ‌ها اینجا نمایش داده می‌شوند.';el('Tracks').append(empty);return;}
    const duration=Math.max(...segments.map(s=>s.endMs),1),groups=new Map();for(const s of segments){const key=`${s.speakerScope||'file'}:${s.speaker??'unknown'}`;if(!groups.has(key))groups.set(key,[]);groups.get(key).push(s);}
    el('TimelineInfo').textContent=`${segments.length} جمله · ${groups.size} مسیر · ${(duration/1000).toFixed(1)} ثانیه`;
    for(const list of groups.values()){
      const row=document.createElement('div');row.className='wb-track';const label=document.createElement('span');label.className='wb-track-label';label.textContent=list[0].speaker==null?'نامشخص':`گوینده ${Number(list[0].speaker)+1}`;
      const lane=document.createElement('div');lane.className='wb-track-lane';lane.style.minWidth=`${Math.max(500,Math.min(5000,duration/1000*14))}px`;lane.style.width='100%';
      for(const s of list){const clip=document.createElement('button');clip.type='button';clip.className='wb-clip';clip.dataset.id=s.id;clip.dataset.ready=s.ready;clip.dataset.selected=s.id===selected?.id;clip.style.left=`${s.startMs/duration*100}%`;clip.style.width=`${Math.max(.4,(s.endMs-s.startMs)/duration*100)}%`;clip.textContent=s.text||s.sourceText||`${s.id+1}`;clip.title=`جمله ${s.id+1} · ${(s.startMs/1000).toFixed(1)} ثانیه · ${s.text}`;clip.setAttribute('aria-label',clip.title);clip.setAttribute('aria-pressed',String(s.id===selected?.id));clip.onclick=()=>select(s.id);lane.append(clip);}
      row.append(label,lane);el('Tracks').append(row);
    }
  }
  function select(id){
    if(dirty){fail('ابتدا تغییرات جملهٔ فعلی را ذخیره کن؛ متن ویرایش‌شده حفظ شده است.');return;}pauseMedia();++previewSerial;selected=job?.segments.find(s=>s.id===id)||null;
    el('Selection').textContent=selected?`جملهٔ ${selected.id+1}${selected.speaker!=null?` · گویندهٔ ${Number(selected.speaker)+1}`:''}`:'بازبینی یک جمله';el('Original').textContent=selected?.sourceText||'متن اصلی این جمله ذخیره نشده است.';el('Text').value=selected?.text||'';el('Start').value=selected?(selected.startMs/1000).toFixed(3):'';el('End').value=selected?(selected.endMs/1000).toFixed(3):'';el('Voice').value=selected?.voiceId||job?.voiceId||'';el('EditState').textContent=selected?.ready?'صدای این جمله آماده است.':'این جمله به ساخت صدا نیاز دارد.';el('SentenceAudio').pause();el('SentenceAudio').hidden=true;
    if(selected){if(el('Video').src)try{el('Video').currentTime=selected.startMs/1000;}catch{}if(el('SourceAudio').src&&el('Mode').value==='source')try{el('SourceAudio').currentTime=selected.startMs/1000;}catch{}}timeline();controls();
  }
  async function refresh(){if(refreshing)return;refreshing=true;try{
    const [state,project]=await Promise.all([send('EASYTS_GET_STATUS'),send('EASYTS_PROJECT_GET')]);busy=phases.includes(state.status?.phase);el('Status').textContent=state.status?.label||'آمادهٔ بازبینی';
    if(!dirty){const next=project.job||null,oldKey=job?`${job.jobKey}:${job.revision||0}:${job.segments.filter(s=>s.ready).length}:${job.segments.length}`:'',newKey=next?`${next.jobKey}:${next.revision||0}:${next.segments.filter(s=>s.ready).length}:${next.segments.length}`:'';job=next;const rendered=job?await StudioDB.get('exports',job.jobKey):null;output=rendered?.revision===(job?.revision||0)&&rendered?.timelineVersion===2?rendered:null;el('Title').textContent=job?.title||'یک فایل وارد کن یا پروژهٔ قبلی را ادامه بده.';if(oldKey!==newKey)select(job?.segments.some(s=>s.id===selected?.id)?selected.id:job?.segments[0]?.id);await media();}
    controls();
  }catch(error){fail(error.message);}finally{refreshing=false;}}
  async function action(fn){if(working)return;working=true;fail('');controls();try{await fn();}catch(error){fail(error.message);}finally{working=false;await refresh();controls();}}
  for(const id of ['Text','Start','End','Voice'])el(id).addEventListener('input',()=>{dirty=true;el('EditState').textContent='تغییرات هنوز ذخیره نشده‌اند.';el('SentenceAudio').pause();controls();});
  el('Save').onclick=()=>action(async()=>{if(!selected)return;const start=Number(el('Start').value),end=Number(el('End').value);if(!el('Text').value.trim()||!Number.isFinite(start)||!Number.isFinite(end)||start<0||end<=start)throw new Error('متن و زمان شروع و پایان را بررسی کن.');await send('EASYTS_PROJECT_EDIT',{jobKey:job.jobKey,revision:job.revision||0,segmentId:selected.id,text:el('Text').value,voiceId:el('Voice').value,startMs:Math.round(start*1000),endMs:Math.round(end*1000)});dirty=false;});
  el('Regen').onclick=()=>action(async()=>{await send('EASYTS_PROJECT_REGENERATE',{jobKey:job.jobKey,segmentId:selected.id});busy=true;});
  el('Preview').onclick=()=>action(async()=>{const serial=++previewSerial,key=job.jobKey,id=selected.id,record=await StudioDB.get('audio',`${key}:${id}`);if(serial!==previewSerial||job?.jobKey!==key||selected?.id!==id)return;if(!record?.blob)throw new Error('صدای این جمله در کش نیست؛ آن را بازسازی کن.');pauseMedia();release('sentence');sentenceUrl=URL.createObjectURL(record.blob);el('SentenceAudio').src=sentenceUrl;el('SentenceAudio').hidden=false;await el('SentenceAudio').play();});
  el('Render').onclick=()=>action(async()=>{await send('EASYTS_RENDER_AUDIO',{jobKey:job.jobKey});busy=true;});
  el('Stop').onclick=()=>action(()=>send('EASYTS_STOP'));
  function download(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);}
  el('Download').onclick=()=>{if(output&&!dirty)download(output.blob,'Easy-ts-dub.wav');};
  el('Srt').onclick=()=>{if(job&&!dirty)download(new Blob(['\uFEFF',EasyTsCore.srt(EasyTsCore.sequentialTimeline(job.segments))],{type:'text/plain;charset=utf-8'}),'Easy-ts-fa.srt');};
  el('Project').onchange=()=>action(async()=>{if(dirty)throw new Error('قبل از تغییر پروژه، ویرایش جمله را ذخیره کن.');if(el('Project').value)await send('EASYTS_PROJECT_RESTORE',{jobKey:el('Project').value});});
  el('File').onchange=()=>action(async()=>{if(dirty)throw new Error('ابتدا ویرایش جمله را ذخیره کن.');const file=el('File').files[0];if(!file)return;if(file.size>200*1024*1024)throw new Error('حداکثر اندازهٔ فایل ۲۰۰ مگابایت است.');const key=`source:${crypto.randomUUID()}`;await StudioDB.put('sources',{key,blob:file,name:file.name,createdAt:Date.now()});await send('EASYTS_FILE_START',{sourceKey:key});busy=true;el('Status').textContent='فایل دریافت شد؛ پردازش در حال شروع است.';el('File').value='';});
  el('Mode').onchange=()=>{pauseMedia();const dub=el('Mode').value==='dub';el('Video').muted=dub;if(dub&&dubUrl){el('SourceAudio').src=dubUrl;el('SourceAudio').hidden=false;}else if(sourceUrl&&el('Video').hidden){el('SourceAudio').src=sourceUrl;el('SourceAudio').hidden=false;}else el('SourceAudio').hidden=true;};
  el('Video').addEventListener('play',()=>{el('SentenceAudio').pause();if(el('Mode').value==='dub'){el('SourceAudio').currentTime=el('Video').currentTime;el('SourceAudio').play().catch(e=>{el('Video').pause();fail(e.message);});}});el('Video').addEventListener('pause',()=>{if(el('Mode').value==='dub')el('SourceAudio').pause();});el('Video').addEventListener('seeking',()=>{if(el('Mode').value==='dub')el('SourceAudio').currentTime=el('Video').currentTime;});el('Video').addEventListener('ratechange',()=>{el('SourceAudio').playbackRate=el('Video').playbackRate;});el('SourceAudio').addEventListener('play',()=>{el('SentenceAudio').pause();if(el('Mode').value==='source')el('Video').pause();});el('SentenceAudio').addEventListener('play',()=>{el('Video').pause();el('SourceAudio').pause();});
  async function listProjects(){const jobs=await StudioDB.all('jobs'),value=el('Project').value;el('Project').replaceChildren(new Option('پروژهٔ فعال',''));for(const item of jobs.sort((a,b)=>(b.createdAt||0)-(a.createdAt||0)))el('Project').append(new Option(item.title||'پروژه',item.jobKey));el('Project').value=value;}
  listProjects().catch(e=>fail(e.message));refresh();poll=setInterval(()=>{refresh();if(!working&&!dirty)listProjects().catch(()=>{});},2500);
  window.addEventListener('beforeunload',event=>{if(dirty){event.preventDefault();event.returnValue='';}});window.addEventListener('unload',()=>{clearInterval(poll);++mediaSerial;++previewSerial;pauseMedia();for(const name of ['source','dub','sentence'])release(name);});
})();
